/* eslint-disable */
/* global WebImporter */

/**
 * Transformer: wknd.site site-wide cleanup.
 *
 * Removes non-authorable site chrome (global header/footer experience
 * fragments, tracking iframe, mobile nav) and social-share widgets so the
 * import contains only page-level authorable content.
 *
 * All selectors below were verified against migration-work/cleaned.html
 * (representative URL: https://wknd.site/us/en/adventures/bali-surf-camp.html).
 *
 * NOTE: The breadcrumb (.breadcrumb.cmp-breadcrumb--fixed) is NOT removed.
 * On this template it is authorable content (section rc1 in
 * page-templates.json), so the generic "remove breadcrumb" rule does not
 * apply here.
 */

const TransformHook = {
  beforeTransform: 'beforeTransform',
  afterTransform: 'afterTransform',
};

export default function transform(hookName, element, payload) {
  if (hookName === TransformHook.beforeTransform) {
    // Non-authorable widgets / tracking that could interfere with parsing or
    // add empty mount points to the output. Verified in cleaned.html:
    //   <div class="sharing ..."><div class="fb-share-button"></div>
    //     <a href="https://www.pinterest.com/pin/create/button/"></a></div>  (social share widget)
    //   <iframe id="destination_publishing_iframe_wkndsite_0" ...>            (Adobe demdex ID sync)
    WebImporter.DOMUtils.remove(element, [
      '.sharing',
      '#destination_publishing_iframe_wkndsite_0',
    ]);

    // Magazine-article template chrome — scoped to that template ONLY so it
    // never touches adventure-detail (whose spec content-fragment has titles)
    // or the homepage. Removes: the duplicate article title (redundant with the
    // page H1), the author byline experience fragment, and the sidebar
    // ("Share this story" + auto "Up Next" list).
    if (payload && payload.template && payload.template.name === 'magazine-article') {
      WebImporter.DOMUtils.remove(element, [
        '.cmp-contentfragment__title',
        'main .cmp-experiencefragment',
        'aside.cmp-layoutcontainer--sidebar',
      ]);
    }
  }

  if (hookName === TransformHook.afterTransform) {
    // Global site chrome (experience fragments) and mobile navigation.
    // Verified in cleaned.html:
    //   <header class="experiencefragment cmp-experiencefragment--header ...">  (nav, logo, search, sign-in, language nav)
    //   <footer class="experiencefragment cmp-experiencefragment--footer ...">  (footer nav, social links, copyright)
    //   <div id="toggleNav"> ... </div>                                        (mobile menu toggle)
    //   <div id="mobileNav" class="cmp-navigation--mobile"> ... </div>         (mobile nav drawer)
    WebImporter.DOMUtils.remove(element, [
      'header.cmp-experiencefragment--header',
      'footer.cmp-experiencefragment--footer',
      '#toggleNav',
      '#mobileNav',
      'iframe',
      'noscript',
    ]);

    // Strip AEM data-layer / accessibility tracking attributes. These are
    // generated by the CMS shell and are never authored. Attribute-only
    // cleanup never removes elements.
    element.querySelectorAll('[data-cmp-data-layer], [data-cmp-data-layer-enabled], [data-cmp-data-layer-name]').forEach((el) => {
      el.removeAttribute('data-cmp-data-layer');
      el.removeAttribute('data-cmp-data-layer-enabled');
      el.removeAttribute('data-cmp-data-layer-name');
    });
  }
}
